# Generated by Django 4.2.4 on 2023-09-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_alter_fileupload_file'),
        ('user', '0003_customuser_profile_picture'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='customuser',
        #     name='profile_picture',
        #     field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileupload'),
        # ),
    ]
