# Generated by Django 4.2.4 on 2023-09-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('PROFILE_PICTURE', 'profile_picture'), ('POST', 'post')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
