# Generated by Django 4.2.4 on 2023-09-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='purpose',
            field=models.CharField(blank=True, choices=[('PROFILE_PICTURE', 'PROFILE_PICTURE'), ('POST', 'POST')], max_length=255, null=True),
        ),
    ]
