# Generated by Django 4.2.4 on 2023-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_remove_fileupload_file_name_alter_fileupload_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
