# Generated by Django 4.2.4 on 2023-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='type',
            field=models.CharField(default='image', max_length=255),
        ),
    ]
