# Generated by Django 4.2.4 on 2023-09-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_post_description_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
