# Generated by Django 4.2.4 on 2023-09-11 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0006_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impression', models.CharField(choices=[('LIKE', 'LIKE'), ('COMMENT', 'COMMENT')], max_length=100)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'impression',
                'verbose_name_plural': 'impressions',
                'db_table': 'impressions',
                'ordering': ['-created_at'],
            },
        ),
    ]
