# Generated by Django 4.2.4 on 2023-09-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
