# Generated by Django 4.2.4 on 2023-10-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
